### ISSUE TITLE
Maintain dependency semver ranges when publishing new versions

### ISSUE THREAD

**Issue by XAMPPRocky** [pksunkara/cargo-workspaces#11]
Hey, I was using `cargo-ws` to publish a new release and I noticed a unintuitive behaviour where it doesn't keep the semver range I set when it needs to update a dependency. For example let's say we have two crates `foo` and `foo-macros`.

### `foo-macros`'s Cargo.toml (before update)
```toml
name = "foo-macros"
version = "0.2.0"
# …
```

### `foo-macros`'s Cargo.toml (after update)
```toml
name = "foo-macros"
version = "0.2.0"
# …
```

### `foo`'s Cargo.toml (before update)
```toml
name = "foo"
version = "0.2.0"
# …
[dependencies]
foo-macros = { version = "=0.2.0", path = "../macros" }
```
### `foo`'s Cargo.toml (after update)
```toml
name = "foo"
version = "0.2.1"
# …
[dependencies]
foo-macros = { version = "0.2.1", path = "../macros" }
```

When I update `foo-macros` to `0.2.1`, `cargo-ws` will also update foo's dependency of `foo-macros` and set it from `=0.2.0` to `0.2.1` so that the crate can be compiled and published. However this now means that the next time I run `cargo ws publish` and release 0.2.2` of `foo-macros` then `foo` will not be updated because `0.2.2` is semver compatible with `0.2.1` which isn't what I want. I want to ensure that both crates are always the same version.
