### ISSUE TITLE
Packages with features do not update their version on cargo ws publish or cargo ws version

### ISSUE THREAD

**Issue by artegoser** [pksunkara/cargo-workspaces#145]
Packages in cargo.toml with `features` do not update their versions.

```toml
symboscript-lexer = { path = "../lexer", version = "0.5.0" }
symboscript-types = { path = "../types", version = "0.5.0", features = [
  "parser",
] }
```

after the cargo ws publish

```toml
symboscript-lexer = { path = "../lexer", version = "0.6.0" }
symboscript-types = { path = "../types", version = "0.5.0", features = [
  "parser",
] }
```

Actually the symboscript-types version has been updated to 0.6.0
