### ISSUE TITLE
`cargo ws rename` misses platform-specific dependencies

### ISSUE THREAD

**Issue by jonas-schievink** [pksunkara/cargo-workspaces#70]
The rust-analyzer auto-publish flow runs `cargo ws rename ra_ap_%n` to prefix all package names with `ra_ap_`, but it has recently started failing because that step leaves this platform-specific dependency declaration untouched:

```toml
[target.'cfg(not(any(target_arch = "wasm32", target_os = "emscripten")))'.dependencies]
toolchain = { path = "../toolchain", version = "0.0.0" }
```

All other dependencies on `toolchain` have been updated to instead say

```toml
toolchain = { path = "../toolchain", version = "0.0.0", package = "ra_ap_toolchain" }
```
