### ISSUE TITLE
Support version in workspace inheritance

### ISSUE THREAD

**Issue by leighmcculloch** [pksunkara/cargo-workspaces#82]
With workspace inheritance released in Rust 1.64 the version of packages can be specified in the workspace Cargo.toml file.

E.g.:
```toml
[workspace]

[workspace.package]
version = "1.0.0"
```

And then the crate Cargo.toml can reference it.

E.g.:
```toml
[package]
version.workspace = true
```

Currently cargo-workspaces can read the versions of crates that use inheritance for their version, but when setting or bumping a version, it will not update the workspace version.
